name: Build Infinity

on:
  workflow_dispatch:
  
env:
  # JAVA_HOME = /usr/lib/jvm/temurin-11-jdk-amd64
  # ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
  # Setting an environment variable with the value of a configuration variable
  VARIANT: ${{ vars.VARIANT_INFINITY }}
  REPO: 'Docile-Alligator/Infinity-For-Reddit'
  REDIRECT_URL: 'http://127.0.0.1'
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN-INFINITY }}
  USER_AGENT: "android:github_ci-app:0.${{ github.run_number }}.${{ github.run_attempt }} built by ${{ github.actor }}"

permissions:
  contents: write

jobs:
  build_job:
    runs-on: ubuntu-22.04
    name: Build Infinity for reddit.

    steps:
      - name: Set-up PATH.
        shell: bash
        run: |
          echo "CAT GITHUB_PATH" && cat $GITHUB_PATH
          echo "ECHO GITHUB_PATH" && echo $GITHUB_PATH
          echo "ECHO PATH" && echo $PATH

          echo "/usr/local/lib/android/sdk/tools/bin:/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH
          cat $GITHUB_PATH

          echo "CAT GITHUB_PATH" && cat $GITHUB_PATH
          echo "ECHO GITHUB_PATH" && echo $GITHUB_PATH
          echo "ECHO PATH" && echo $PATH
        
      - name: Checkout Infinity-For-Reddit repository.
        if: ${{ env.VARIANT == 'git' }}
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
          repository: ${{ env.REPO }}

      - name: Fetch source archive.
        if: ${{ env.VARIANT != 'git' }}
        shell: bash
        run: |
          latest_tag=$(curl -s "https://api.github.com/repos/${REPO}/releases/latest" \
            | grep "\"tag_name\":" | cut -d \" -f 4)
              
          latest_url="https://github.com/${REPO}/archive/refs/tags/${latest_tag}.tar.gz"
            
          wget -O "${REPO#*/}.tar.gz" "${latest_url}" && \
          tar xf  "${REPO#*/}.tar.gz" && \
          mv "${REPO#*/}-${latest_tag#*v}" "${REPO#*/}" && \
          rm -f "${REPO#*/}.tar.gz"

          echo "CAT GITHUB_PATH" && cat $GITHUB_PATH
          echo "ECHO GITHUB_PATH" && echo $GITHUB_PATH
          echo "ECHO PATH" && echo $PATH
          
      - name: Build source.
        shell: bash
        run: |
          echo "CAT GITHUB_PATH" && cat $GITHUB_PATH
          echo "ECHO GITHUB_PATH" && echo $GITHUB_PATH
          echo "ECHO PATH" && echo $PATH

          apt-get --quiet update
          apt-get --quiet upgrade
          
#          sed -i -e "s#\"NOe2iKrPPzwscA\"#\"${api_token}\"#" \
#              -e "s#\"infinity://localhost\"#\"${redirect_uri}\"#" \
#              -e "s#public static final String USER_AGENT = \".*\";#public static final String USER_AGENT = \"${user_agent}\";#" "${apiutils_file}"
            
