name: "Build Infinity for reddit."

on:
  workflow_dispatch:

env:
  # JAVA_HOME = /usr/lib/jvm/temurin-11-jdk-amd64
  # ANDROID_SDK_ROOT = /usr/local/lib/android/sdk
  # Setting an environment variable with the value of a configuration variable
  VARIANT: ${{ vars.VARIANT_INFINITY }}
  REPO: 'Docile-Alligator/Infinity-For-Reddit'
  REDIRECT_URL: 'http://127.0.0.1'
  API_TOKEN: ${{ secrets.API_TOKEN-INFINITY }}
  USER_AGENT: "android:github_ci-app:0.${{ github.run_number }}.${{ github.run_attempt }} built by ${{ github.actor }}"
  # setup colors
  RED_COLOR: '\e[1;31m'
  ORANGE_COLOR: '\e[1;33m'
  BLUE_COLOR: '\e[0;34m'
  BOLD_TEXT: '\e[1m'
  UNSET_COLOR: '\e[0m'

permissions:
  contents: read

jobs:
  build_job:
    runs-on: ubuntu-22.04

    steps:
      - name: "Set-up PATH and update build tools."
        shell: bash
        run: |
          echo "/usr/local/lib/android/sdk/tools/bin:/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH
          sudo -E /usr/local/lib/android/sdk/tools/bin/sdkmanager "platforms;android-33" "build-tools;33.0.0" &> /dev/null

      - name: "Checkout Infinity-For-Reddit repository."
        if: ${{ env.VARIANT == 'git' }}
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          show-progress: false
          repository: ${{ env.REPO }}

      - name: "Fetch source archive."
        if: ${{ env.VARIANT != 'git' }}
        shell: bash
        run: |
          set -x
          printf "${ORANGE_COLOR}[IMPORTANT]\n"
          printf "Using archive as source package.${UNSET_COLOR}\n"
          set +x

          latest_tag=$(curl -s "https://api.github.com/repos/${REPO}/releases/latest" \
            | grep "\"tag_name\":" | cut -d \" -f 4)

          latest_url="https://github.com/${REPO}/archive/refs/tags/${latest_tag}.tar.gz"

          wget --quiet -O "${REPO#*/}.tar.gz" "${latest_url}" && \
          tar xf "${REPO#*/}.tar.gz" && \
          mv "${REPO#*/}-${latest_tag#*v}" "${REPO#*/}" && \
          rm -f "${REPO#*/}.tar.gz"

      - name: "Build source and compress APKs."
        shell: bash
        run: |
          cd "${REPO#*/}"
          if [[ -n "${API_TOKEN}" ]]; then
            sed -i -e "s#\"NOe2iKrPPzwscA\"#\"${API_TOKEN}\"#" \
                -e "s#\"infinity://localhost\"#\"${REDIRECT_URL}\"#" \
                -e "s#public static final String USER_AGENT = \".*\";#public static final String USER_AGENT = \"${USER_AGENT}\";#" "${apiutils_file}"
          #TODO: Compress APKs.
          else
            set -x
            printf "${ORANGE_COLOR}NOTE: API_TOKEN not provided, building debug apk.${UNSET_COLOR}\n\n"
            set +
            ./gradlew assembleDebug
            echo "APK_VARIANT_DEBUG=true" >> "$GITHUB_ENV"
            mv "~/${REPO#*/}/app/build/outputs/apk/debug/app-debug.apk" "~/infinity-debug.apk"
          fi

      - uses: actions/upload-artifact@v3
        name: Upload debug APK as artifact.
        if: ${{ env.APK_VARIANT_DEBUG == 'true' }}
        with:
          name: Upload debug APK.
          path: /home/workspace/infinity-debug.apk

      - uses: actions/upload-artifact@v3
        if: ${{ env.APK_VARIANT_DEBUG == 'true' }}
        with:
          name: Upload debug APK.
          path: /home/workspace/infinity-debug.apk

      - name: "Upload compressed APK."
        if: ${{ env.APK_VARIANT_DEBUG != 'true' }}
        env:
          SSHKEY: ${{ secrets.SSHKEY }}
          REMOTE: ${{ secrets.REMOTE_ANDROID }}
          HOST: ${{ secrets.HOST }}
        shell: bash
        run: |        
          if ! grep -Fxq "$HOST" "/home/runner/.ssh/known_hosts" &> /dev/null; then
            if ! echo "$HOST" | tee -a "/home/runner/.ssh/known_hosts" &> /dev/null; then
              echo -e "${RED_COLOR}${BOLD_TEXT}Failed to append REMOTE to '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}"
              exit 1
            fi
            echo -e "${BLUE_COLOR}${BOLD_TEXT}REMOTE appended to '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}"

            chmod -v 0600 "/home/runner/.ssh/known_hosts" &> /dev/null && \
              echo -e "${BLUE_COLOR}${BOLD_TEXT}Corrected permissions of '~/.ssh/known_hosts' - proceeding.{UNSET_COLOR}" || \
                (echo -e "${RED_COLOR}${BOLD_TEXT}Failed to set correct permissions of '~/.ssh/known_hosts' - aborting.${UNSET_COLOR}" \
                  && exit 1 )
          fi

          if [[ -f "/home/runner/.ssh/id_ed25519" ]]; then
            echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519.bak" &> /dev/null
            if ! diff "/home/runner/.ssh/id_ed25519" "/home/runner/.ssh/id_ed25519.bak" &> /dev/null; then
              mv -v "/home/runner/.ssh/id_ed25519.bak" "/home/runner/.ssh/id_ed25519" &> /dev/null
              echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
            fi
          else
            echo -e "$SSHKEY" | tee "/home/runner/.ssh/id_ed25519" &> /dev/null
            echo -e "${BLUE_COLOR}${BOLD_TEXT}Private SSH Key created - proceeding.{UNSET_COLOR}"
          fi

          chmod -v 0600 "/home/runner/.ssh/id_ed25519" &> /dev/null

          if rsync -a --delete -e "ssh -v -i /home/runner/.ssh/id_ed25519" "$GITHUB_WORKSPACE/repo/" "$REMOTE" &> /dev/null; then
            echo -e "${BLUE_COLOR}${BOLD_TEXT}Successfully synced files - proceeding.{UNSET_COLOR}"
          else
            echo -e "${RED_COLOR}${BOLD_TEXT}Failed to sync files - aborting.${UNSET_COLOR}"
            return 1
          fi || (exit 1)
